# Create an Azure pipeline with a CI trigger for main branch.
# The pipeline should run the following terraform commands to deploy
# the file main.tf, in the root of the repository:
# - terraform init
# - terraform plan
# - terraform apply
#
# The pipeline should use an Azure DevOps Service connection named "tf-wi-cmh"
# and should run on an self-hosted agent pool named "tf-mi"

trigger:
  branches:
    include:
      - main

pool:
  name: tf-mi

variables: 
  serviceConnection: 'tf-wi-cmh'
  stateStorage: 'cmhtfstatesa'
  stateContainer: 'tfstate'
  stateKey: 'terraform.tfstate'
  resourceGroup: 'rg-tf'

steps:
  - checkout: self
    persistCredentials: true

  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTaskV4@4
    displayName: tf init
    inputs:
      provider: azurerm
      command: init
      backendAzureRmResourceGroupName: $(resourceGroup)
      backendServiceArm: $(serviceConnection)
      backendAzureRmStorageAccountName: $(stateStorage)
      backendAzureRmContainerName: $(stateContainer)
      backendAzureRmKey: $(stateKey)

  # - script: |
  #     terraform init
  #     terraform plan
  #     terraform apply -auto-approve
  #   displayName: 'Terraform commands'